### ISSUE TITLE
Issues on version checks

### ISSUE THREAD

**Issue by timothyqiu** [jiacai2050/zig-curl#14]
There're three checks with `CURL_AT_LEAST_VERSION`.

1. `CURLOPT_CAINFO_BLOB` is added in `7.77.0`, but `7.81.0` is checked.
    https://github.com/jiacai2050/zig-curl/blob/c1f6fb8ee421b264a6d8086e91fed05dbd8f7039/src/Easy.zig#L352-L355
2. `curl_easy_header` is added in `7.83.0`, but `7.84.0` is checked.
    https://github.com/jiacai2050/zig-curl/blob/c1f6fb8ee421b264a6d8086e91fed05dbd8f7039/src/util.zig#L58-L59
3. `curl_easy_reset` is added in `7.12.1`, but `7.12.0` is checked. Anyway, `CURL_AT_LEAST_VERSION` itself is only available since `7.43.0`.
    https://github.com/jiacai2050/zig-curl/blob/c1f6fb8ee421b264a6d8086e91fed05dbd8f7039/src/util.zig#L63-L64

**Comment by jiacai2050** [comment]
# 1 
> This option is supported by the BearSSL (since 7.79.0), mbedTLS (since 7.81.0), rustls (since 7.82.0), wolfSSL (since 8.2.0), OpenSSL, Secure Transport and Schannel backends.

I think we are targeting mbedTLS, however we have no idea which backends users may use, so we can relax this check.

# 2
> This API was made official and is provided for real starting in libcurl 7.84.0.
https://ec.haxx.se/helpers/headerapi/index.html
 
# 3

I will push a fix for this.

**Comment by timothyqiu** [comment]
> This API was made official and is provided for real starting in libcurl 7.84.0.

We should rely on the documentation rather than an ebook.

This is definitely a mistake of that book.

- The [official documentation](https://curl.se/libcurl/c/curl_easy_header.html) shows it's available since 7.83.0.
- `curl_easy_header` exists in 7.83.0 codebase.
- [Release Notes of 7.83.0](https://github.com/curl/curl/blob/curl-7_83_0/RELEASE-NOTES) explicitly states header APIs like `curl_easy_header` are added in that version, so it's official instead of experimental.

---

https://github.com/jiacai2050/zig-curl/blob/662c547e6eeeeee0ec373d2f75cf6c953e0d9cc1/src/util.zig#L63-L69

This check is redundant too. The symbol does not exist before 7.43.0. So this code either always succeed or fail to compile because `CURL_AT_LEAST_VERSION` does not exist (instead of emitting `Libcurl version must at least 7.43.0`).

**Comment by jiacai2050** [comment]
> We should rely on the documentation rather than an ebook.
> This is definitely a mistake of that book.

I think no confusion here, the doc says it's available in 7.83, the ebook says it's stable in 7.84. We can check it here: 

https://github.com/curl/curl/blob/curl-7_84_0/RELEASE-NOTES#L71

Also ebook is written by [Daniel](https://ec.haxx.se/index.html#author), the author of libcurl.

**Comment by jiacai2050** [comment]
> This check is still redundant. The symbol does not exist before 7.43.0. So this code either always succeed or fail to compile because `CURL_AT_LEAST_VERSION` does not exist (instead of emitting `Libcurl version must at least 7.43.0`).

You're right, `c.hasDecl(CURL_AT_LEAST_VERSION)` should be used here.
